spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lms?createDatabaseIfNotExist=true
    username: root
    password: Razak@2005

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mvc:
    throw-exception-if-no-handler-found: true

  web:
    resources:
      add-mappings: false

app:
  jwtSecret: mySecretKey1234567890abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
  jwtExpirationMs: 86400000
  default-admin:
    username: admin
    password: admin123
    email: admin@gmail.com

logging:
  level:
    com.lms.dev: DEBUG
    org.springframework.security: DEBUG
